### ISSUE TITLE
Change rule to allow surrogates

### ISSUE THREAD

**Issue by stevenatkin** [w3c/bp-i18n-specdev#11]
http://w3c.github.io/bp-i18n-specdev/#char_surrogate

I think this rule is incorrect in the "Including and excluding character ranges" section of checklist.

Specifications MUST NOT allow the use of surrogate code points.

I think it should be MUST ALLOW.

**Comment by aphillips** [comment]
Surrogate != supplementary ?

**Comment by r12a** [comment]
see https://github.com/w3c/bp-i18n-specdev/issues/10

Surrogates are disallowed as code points. Supplementary characters are fine. See http://w3c.github.io/bp-i18n-specdev/#char_exclude

> Specifications SHOULD NOT arbitrarily exclude code points from the full range of Unicode code points from U+0000 to U+10FFFF inclusive

**Comment by stevenatkin** [comment]
I agree that's fine. We will have to see if spec authors fully understand this distinction.
