### ISSUE TITLE
Imageize invisible character examples

### ISSUE THREAD

**Issue by aphillips** [w3c/bp-i18n-specdev#114]
See: https://github.com/w3c/bp-i18n-specdev/pull/113#issuecomment-1654660980

We need to add images for invisible characters in character template entries used in specdev because:

"This dog food is yummy" 🐶 

@r12a could you make the images? I'll make a list of what we need.

**Comment by aphillips** [comment]
Characters needed:

200F
200E
0009
000A
000B
000C
000D
0020
0085
00A0
1680
2000-200A
2028
2029
202F
205F
3000
FEFF
007F

**Comment by r12a** [comment]
You can find the images as follows: https://r12a.github.io/c/<block_name>/large/<hex>.png

eg. https://r12a.github.io/c/General_Punctuation/large/200F.png

The block name should be exactly as used in Unicode, including caps, and _ for spaces.

Just drag the result from the browser to the images directory.

**Comment by r12a** [comment]
Alternatively, you can just bring up each character on UniView and drag the (large) image to the directory. Eg.
https://r12a.github.io/uniview/?char=000C

**Comment by aphillips** [comment]
thanks @r12a!!

**Comment by aphillips** [comment]
This change has reached production.
