### ISSUE TITLE
establish a glossary?

### ISSUE THREAD

**Issue by aphillips** [w3c/bp-i18n-specdev#12]
Section 2 "Resources" begins:

> Here we are talking about an independent unit of data.

This is consistent with the definition of "resource" that we developed in Charmod-norm. In other cases we have defined terminology in other Notes, specs, or articles that would be useful "all in one place" (much like Unicode's glossary). Should spec dev try to amalgamate all our definitions?

In the case of "resource" we should copy the definition from Charmod-norm.

One particular set of definitions that I like and which might be useful in a central location are sections 2.1 and 2.2 from LTLI: http://w3c.github.io/ltli/#language-terminology

**Comment by duerst** [comment]
'resource' is an important term in Web architecture (see e.g. https://www.w3.org/TR/webarch/#id-resources, and also http://tools.ietf.org/html/rfc3986#section-1). I think it would be higly desirable if there weren't a separate definition for i18n purposes.
Please also note the following sentence:
"What some specifications, in particular the HTTP specification, refer to as a representation is referred to in this specification as a resource. [HTTP]" (from https://www.w3.org/TR/html5/infrastructure.html#resources).

**Comment by xfq** [comment]
Now we have https://w3c.github.io/i18n-glossary/

**Comment by aphillips** [comment]
We build i18n-glossary since this issue was created. Close this?
