### ISSUE TITLE
improve description of BCP 47

### ISSUE THREAD

**Issue by aphillips** [w3c/bp-i18n-specdev#13]
http://w3c.github.io/bp-i18n-specdev/#lang_use_bcp47

The description of BCP 47 could use some help, as it is "backwards looking"

> BCP 47 defines a method to combine subtags in order to create a much more powerful notation for language tags than that provided by the old ISO lists, but it is also backwards compatible with the ISO lists.

I'd suggest:

> BCP 47 is the language tag system used by Internet and Web standards (and many other places). It defines a method of using _subtags_ based on several ISO standards and a registration process to describe language.

**Comment by asmusf** [comment]
I like the new language, but perhaps it's best to not lose the explicit statement of backward compatibility. Why not add at the end: "it is also backwards compatible with the [ISO lists.]" (The text in [ ] should probably be rephrased a bit, as "ISO lists" isn't very clear.)

**Comment by aphillips** [comment]
I adapted and expanded on these:

> BCP 47 is the [language tag](https://www.w3.org/TR/i18n-glossary/#def_language_tag) system used by Internet and Web standards (and many other places). It defines a method of using subtags from an IANA registry to form a string to describe the language of content. The subtags in the registry are primarily based on (and maintain strict compatibility with) ISO and UN standards for identifying languages, scripts, regions, and countries. BCP47 also forms the basis for [Unicode locales](https://www.w3.org/TR/i18n-glossary/#def_unicode_locale).

**Comment by r12a** [comment]
[from Addison]

here was an existing description of BCP47 but several suggestions for improvements. I edited the description [5] in line with these comments. Richard has already called out beauty and elegance of the resulting prose 😉. 

![image004](https://user-images.githubusercontent.com/4839211/167409616-adb9017c-0586-4d3f-a605-3c3365f56521.png)

**Comment by r12a** [comment]
suggestion: "string to describe the language of content" -> "string which describes the language of content"  (breaks up the to .. to)

**Comment by aphillips** [comment]
Done.
