### ISSUE TITLE
mention the language subtag registry

### ISSUE THREAD

**Issue by aphillips** [w3c/bp-i18n-specdev#14]
I'd add a new requirement just under http://w3c.github.io/bp-i18n-specdev/#lang_use_bcp47. Something like:

> **Use the Language Subtag Registry instead of references or lists of codes extracted from ISO 639 or ISO 3166**
> 
> As part of BCP 47, IANA maintains the language subtag registry, which is a publicly available, machine-readable list of valid subtags for use in language tags. While this registry is based on underlying ISO standards, such as ISO 639 (languages) and ISO 3166 (regions), the list is actively maintained, stabilized, and comprehensive in ways that other lists found on the Internet may not be.

**Comment by xfq** [comment]
Seems to be fixed now?

**Comment by aphillips** [comment]
Fixed.
