### ISSUE TITLE
Strong directional formatting characters

### ISSUE THREAD

**Issue by xfq** [w3c/bp-i18n-specdev#143]
Rendered: https://w3c.github.io/bp-i18n-specdev/#rlmlrm

Source: https://github.com/w3c/bp-i18n-specdev/blob/f429a3259b5402322927b48c19de7cf5eedc9190/index.html#L881-L882

When this text is rendered in the browser, "W3C" is already on the left. Should `dir="rtl"` be removed here?

**Comment by ntounsi** [comment]
Or perhaps say : 
... to make the text W3C appear to the left of the Hebrew text _as_ in the following example.
