### ISSUE TITLE
Should include advice on what "White-space" is.

### ISSUE THREAD

**Issue by spemberton** [w3c/bp-i18n-specdev#15]
Many specs talk about white space, or "space-separated" things (indeed this very spec does).

They then either fail to list what white-space means, or include a list of characters that they are willing to accept as white space.

The spec community really needs more help in defining white-space. In particular, Unicode has specifications for white-space, that (imo) ought to be used more by spec writers, so that "white-space" is whatever Unicode says it is, rather than everyone making it up themselves.

**Comment by spemberton** [comment]
See http://unicode.org/Public/UNIDATA/PropList.txt

**Comment by johnwcowan** [comment]
I almost, but not quite, entirely disagree.

The Unicode definition of whitespace is meant to be extensive, and includes every character that has a width or height (no fully invisible characters) but doesn't put ink on the paper/screen (no graphic characters).  That does _not_ mean that all of them are suitable for specifications.  Specs should allow no whitespace except ASCII space, tab, carriage return, and newline.  Anything else is just an invitation to confusion and misunderstanding.

**Comment by spemberton** [comment]
Let me give an example of a case we are struggling with. We have a function that is defined to remove all whitespace from a string. We really need advice on which characters should then be removed; should we be removing U+2000-2009? John apparently thinks not. Well if not, why not? We would like an explanation of what ought to be considered whitespace, and what not.

**Comment by johnwcowan** [comment]
The other whitespaces are for specialized purposes and shouldn't be disturbed.  For example, Mongolian narrow no-break space is part of the way certain Mongolian words are spelled: if you remove it, you end up with a different Mongolian word.   What is more, new whitespace characters can be added at any time.  For stability and performance, just stick to the simple ASCII whitespace.

**Comment by spemberton** [comment]
Don't give the answer here! Give it in the spec that we are discussing. I can't imagine we are the only group struggling with the white space issue. This thread is about internationalisation issues that the spec doesn't answer, that it should.

By the way, the fact that whitespace could be added at any time is an argument for *using* the Unicode definition of whitespace, and not an argument against it.

But what about U+2000-2009. Why wouldn't I want them removed if I pasted some text into a form that doesn't accept whitespace?

**Comment by r12a** [comment]
> Don't give the answer here! Give it in the spec that we are discussing.

@spemberton what do you mean?  Add the information to https://w3c.github.io/bp-i18n-specdev/ or add the information to the spec you are struggling with (for which a link would be useful, btw)?

You asked this question some time ago, and when we discussed this in the i18n WG telecon our conclusion was that what should be counted as 'white space' depends very much on what the application is trying to do.

I agree with John that it's very unlikely that you'd want to remove NNBSP, whatever you're doing, since that's used almost like a letter in Mongolian, even though it just looks like a space or gap - removing it would really screw up the meaning of the text. By the way, does your application for white space removal care about invisible characters (such as Mongolian variant selectors?) or are you just worried about blank gaps appearing between other characters?  And what is the motivation for removing 'white space' in your case?

**Comment by johnwcowan** [comment]
Indeed.  Per contra, Ogham feather space is a Unicode whitespace character but isn't blank: it puts ink on the screen/paper.  As for the fixed width spaces U+2000-09, they aren't really interesting for anything, being a carryover from analog typesetting.

**Comment by r12a** [comment]
Speaking of which, there are also word separators which aren't spaces and also aren't white space characters according to Unicode, such as ፡ ‎1361  ETHIOPIC WORDSPACE.  In your use case, would you be worried about those hanging around? Again, it depends what you want to achieve by eliminating white space.

**Comment by spemberton** [comment]
Hi Richard,

> @spemberton what do you mean? Add the information to https://w3c.github.io/bp-i18n-specdev/
> or add the information to the spec you are struggling with (for which a link would be useful, btw)?

The former, since this thread is part of a discussion of what ought to be in that spec. 
Groups were asked to comment on what they would like to see in the spec, 
and so I sent in two suggestions 1) help on whitespace 2) help on what a 'letter' is.

The link: https://www.w3.org/community/xformsusers/wiki/XForms_2.0

> You asked this question some time ago, and when we discussed this in the i18n WG telecon
> our conclusion was that what should be counted as 'white space' depends very much on
> what the application is trying to do.

I quite agree.

> I agree with John that it's very unlikely that you'd want to remove NNBSP, whatever you're doing,
> since that's used almost like a letter in Mongolian, even though it just looks like a space or gap
> - removing it would really screw up the meaning of the text. 

I note that Unicode doesn't classify NNBSP as Mongolian, even if it is often used in that context.
So apparently NNBSP is dependent on its context, and thus it may depend on its context whether it
should be removed or not (which is a shame; it would be better to *not* use NNBSP in Mongolian,
and have a special character that reflects this special usage.)

> By the way, does your application for white space removal care about invisible characters
> (such as Mongolian variant selectors?) or are you just worried about blank gaps appearing
> between other characters? And what is the motivation for removing 'white space' in your case?

We have a meta-usecase. There are certain values (in the world) that do not permit spaces in certain places, but that may be input with spaces nevertheless. Our classic example is credit card numbers, which people often input with spaces, but which need to be removed. But don't fixate on that one example, because there's an unbounded number of them: people copy and pasting numbers from a report where the numbers have been formatted with spaces, addresses where only single spaces are permitted, email addresses where leading and trailing spaces need to be elided. Values often come from copy/pasting, as well as keyboard input. We don't know all the use cases people have, but we do allow people to mark values as needing to have whitespace removed or compressed on input.

There is no good resource that we could find that helps with the definition of whitespace. Different specs seem to do different things. bp-i18n-specdev seems like an ideal candidate.

**Comment by spemberton** [comment]
Let me try and expand just a little: I occasionally find NBSPs in my input, because in certain contexts ctrl-space generates an NBSP. I wouldn't want to be told that "1234 5678 9012 3456" was an invalid credit card number just because there happened to be an NBSP in there by mistake. 

We as spec designers have little knowledge of what other space characters other cultures may generate from their keyboards, but in any case, if they generate them, and they consider them whitespace, they will expect them to be treated as whitespace by our system. This is why we turn to your group to explain to us what is good behaviour when confronted with input from different cultures.

**Comment by spemberton** [comment]
By the way, U+1361 mentioned above is classified in Unicode as Punctuation (Po), not as whitespace.

**Comment by johnwcowan** [comment]
On Fri, Mar 24, 2017 at 12:15 PM, Steven Pemberton <notifications@github.com
> wrote:

> By the way, U+1361 mentioned above is classified in Unicode as Punctuation
> (Po), not as whitespace.


I've filed an erratum about the inconsistent classification of
word-separator characters that have ink in Unicode:  most are Po but U+1680
is Zs.  Hopefully this will be fixed in 10.0.

-- 
John Cowan          http://vrici.lojban.org/~cowan        cowan@ccil.org
Gules six bars argent on a canton azure 50 mullets argent
six five six five six five six five and six
   --blazoning the U.S. flag <http://web.meson.org/blazonserver>
