### ISSUE TITLE
Should also mention ALM beside LRM and RLM

### ISSUE THREAD

**Issue by lkemmel** [w3c/bp-i18n-specdev#18]
In 5.2.5 ALM (U+061C ARABIC LETTER MARK) should be mentioned as well:
- In the caption: "RLM and LRM" ==> replace with "RLM, ALM, and LRM"
- "A word about the Unicode characters U+200F RIGHT-TO-LEFT MARK (RLM) and U+200E LEFT-TO-RIGHT MARK (LRM) is warranted at this point."
  ==> "A word about the Unicode characters U+200F RIGHT-TO-LEFT MARK (RLM), U+061C ARABIC LETTER MARK (ALM), and U+200E LEFT-TO-RIGHT MARK (LRM) is warranted at this point (unless is used to force base direction when is estimated according to first-strong)."
- "The first point to be clear about is that neither RLM, nor LRM establish the base direction for a range of text.  They are simply invisible characters with strong directional properties."
  ==> "The first point to be clear about is that none of the RLM, ALM, or LRM establish the base direction for a range of text.  They are simply invisible characters with strong directional properties."
- "Of course, if you are detecting base direction using first-strong heuristics then RLM and LRM can be useful for setting the base direction where the text in question begins with something that would otherwise give the wrong result, eg. "
  ==> "Of course, if you are detecting base direction using first-strong heuristics then RLM, ALM, and LRM can be useful for setting the base direction where the text in question begins with something that would otherwise give the wrong result, eg. "

That said, it should be mentioned that "ALM is still not widely supported."

**Comment by r12a** [comment]
For background on ALM, see:

- https://r12a.github.io/scripts/arab/arb.html#expressions
- https://r12a.github.io/scripts/arab/block.html#ar061C
