### ISSUE TITLE
Use locale-neutral data representations

### ISSUE THREAD

**Issue by r12a** [w3c/bp-i18n-specdev#19]
mention some of this stuff
http://philarcher1.github.io/dwbp/bp.html#LocaleParametersMetadata

**Comment by r12a** [comment]
Link broken. Need to check with PhilA.

**Comment by aphillips** [comment]
Start here? https://www.w3.org/TR/dwbp/#LocaleParametersMetadata

**Comment by aphillips** [comment]
I adapted the dwbp text to our needs and added an acknowledgement in my most recent PR.

**Comment by r12a** [comment]
[from Addison]

This issue called for the incorporation of guidence found in “Data for the Web: Best Practices” [DWBP][7]. Starting from the text found there, I reworded to suit this context [6]. This also resulted in adding references to DWBP and XMLSchema-2 and an acknowledgement 

![image005](https://user-images.githubusercontent.com/4839211/167411075-e9c1dde3-6096-42c2-bfb1-f446e3baebef.png)

**Comment by r12a** [comment]
How about "When defining internal data formats,..." ?

**Comment by aphillips** [comment]
@r12a Why only "internal"? That suggests that the values are not for interchange whereas I think you mean "not for presentation"

Or perhaps we should take away the qualifier and just make it `Use locale-neutral serialization forms` or perhaps `Prefer locale-neutral serialization forms`?

**Comment by r12a** [comment]
Mm. For me 'internal' doesn't exclude what's interchanged.

How about "When defining data format representations that are used internally or for data interchange, ..." ?

**Comment by aphillips** [comment]
What's the distinction you're trying to make with "internal"? I want to capture the distinction accurately.

**Comment by r12a** [comment]
As you said, not for presentation, but defining it that way is a little bit of a round about way of talking.  I was hoping we could more directly express the field of use.  The HTML spec refers to this as the 'wire format'.

**Comment by aphillips** [comment]
Keeping this one open for now.

**Comment by aphillips** [comment]
I'm not sure why I kept this open.

@r12a is there anything we should change here?
