### ISSUE TITLE
Spell out internationalization in place of 'i18n'

### ISSUE THREAD

**Issue by aphillips** [w3c/bp-i18n-specdev#2]
Many places in the document the conventional acronym 'i18n' is used, but the document will be more accessible to users if we use the word spelled out instead.

**Comment by r12a** [comment]
it's only used twice, as far as i can see, in 'I18n WG' immediately after "The Internationalization (i18n) WG tries...".  Am i missing something?

http://w3c.github.io/bp-i18n-specdev/#intro

**Comment by aphillips** [comment]
Look at the date on that comment! I think you already fixed it.
