### ISSUE TITLE
Value of default direction

### ISSUE THREAD

**Issue by r12a** [w3c/bp-i18n-specdev#21]
3.3.1 Setting the default base direction
https://w3c.github.io/bp-i18n-specdev/#bidi_res_default

> The default base direction, in the absence of other information, should be LTR. 

Should we change this to say AUTO?

**Comment by matial** [comment]
I am in favor of changing the default base direction to AUTO. If the text in question contains no RTL characters, there will be no difference in effect between the default being LTR or AUTO.
If the text does contain RTL characters, then this is the use case for AUTO.
The one counter example would be when the author judges that the LTR direction is mandated even when the first strong character is RTL, so changing the default to AUTO would require the author to explicitly specify the direction as LTR. 
I expect that such a case is more unlikely than when AUTO does the right thing.

**Comment by aphillips** [comment]
Guidance please? Should I make this change? I suspect that I should with the addition of some explanatory text.

**Comment by xfq** [comment]
I agree with changing it to auto. auto seems to have less chance of error than ltr when metadata is not available, and it is consistent with specs like [Notifications API](https://notifications.spec.whatwg.org/#dom-notificationoptions-dir) and [Web Application Manifest](https://www.w3.org/TR/appmanifest/#dir-member).

**Comment by aphillips** [comment]
tpac 2024: make the change

**Comment by aphillips** [comment]
Changed and published to TR
