### ISSUE TITLE
Personal names section

### ISSUE THREAD

**Issue by r12a** [w3c/bp-i18n-specdev#24]
New section drafted. Needs review.

http://w3c.github.io/bp-i18n-specdev/#loc_names

**Comment by aphillips** [comment]
@r12a Per our discussion in telecon, maybe consider bringing material from the personal names doc into specdev here? Some of the guidance probably needs to make it in here and some of the terminology needs to go in the glossary. Thoughts?

**Comment by xfq** [comment]
Do you mean putting the content of [Personal names around the world](https://www.w3.org/International/questions/qa-personal-names) in specdev? But that article isn't just for spec developers, it's useful for Web developers too.

**Comment by r12a** [comment]
@xfq i think it would mean adding to specdev summaries of the explanatory text in the PNATW article, but probably pointing back to that article for some of the more complicated examples.  The article would still exist as is, but it would be easier to read specdev.  Note that we also have https://www.w3.org/International/techniques/authoring-html#localnames for content authors (which iirc may have slightly different set of requirements or wording of requirements, based on the audience).

**Comment by r12a** [comment]
@aphillips, i could give this a try if you're not planning on changing that section yourself (ie. i want to avoid conflicts).  Let me know if you find anything about the PR for section 4.1 that i submitted today which would influence how i go about this section.

**Comment by aphillips** [comment]
@r12a Jump right in! I'll avoid that section. I'll also check out the PR.
