### ISSUE TITLE
The `translate` attribute

### ISSUE THREAD

**Issue by Malvoz** [w3c/bp-i18n-specdev#35]
Has the [`translate` attribute](https://html.spec.whatwg.org/multipage/dom.html#the-translate-attribute) been overlooked or is there a reason it is not mentioned in the spec?

User agents, browser extensions and other tools offering translation services may render parts of a document confusing to users where otherwise e.g. the `translate="no"` attribute-value pair would help, for example it could be considered incorrect to translate a street name or the name of an organization in some cases.

**Comment by r12a** [comment]
I think it's an omission that we don't advise spec developers to provide a feature for inhibiting or promoting translation (or other things described in the ITS spec).  (Noting, of course, that the doc you link to gives advice to spec developers.  It _is_ mentioned in the [equivalent for content authors](https://www.w3.org/International/techniques/authoring-html.en?open=markup&open=translate#translate).)

**Comment by Malvoz** [comment]
Oh yes that makes sense, brain fart. Thanks. :)
