### ISSUE TITLE
Sync the checklist view with ED (or /TR version)

### ISSUE THREAD

**Issue by xfq** [w3c/bp-i18n-specdev#44]
Some recently added text (like [cursive text](https://w3c.github.io/bp-i18n-specdev/#cursive)) is not in the [checklist view](https://www.w3.org/International/techniques/developing-specs?collapse). I think it would be useful to sync the checklist view with the specdev ED (or /TR version).

**Comment by r12a** [comment]
+1.  It's currently a manual process.  I don't yet have a clear idea how to make it fully automatic, but i'll give it some thought. In the meantime, i'll take an action to update the checklist view as soon as we do the publication update.

**Comment by r12a** [comment]
The checklist has now been integrated into the specdev doc.
