### ISSUE TITLE
Duplicated References section

### ISSUE THREAD

**Issue by xfq** [w3c/bp-i18n-specdev#45]
There are two References sections:

* https://w3c.github.io/bp-i18n-specdev/#app_b
* https://w3c.github.io/bp-i18n-specdev/#references

We should merge them into one.

**Comment by r12a** [comment]
I agree. Are you ok to do that while working on the other stuff?

**Comment by xfq** [comment]
Fixed in https://github.com/w3c/bp-i18n-specdev/commit/cdbf6d5d5a9e73d56ba8c5f9cc1a7effd117b539
