### ISSUE TITLE
Add text about sorting code units

### ISSUE THREAD

**Issue by aphillips** [w3c/bp-i18n-specdev#62]
Quoting https://github.com/w3c/i18n-activity/issues/362 :

I think it would be useful to add something to specdev describing the aims and limitations of the sort they are proposing. We'd need to create a succinct do/don't sentence, then add a paragraph of explanation, which could include:

>    This matches the Array.prototype.sort on an Array of Strings. This ordering compares the 16-bit code units in each string, producing a highly efficient, consistent, and deterministic sort order. The resulting list will not match any particular alphabet or lexicographical order, particularly for code points represented by a surrogate pair.

**Comment by r12a** [comment]
[from Addison]

Section 5.7 talks about sorting and only included four requirements from Charmod-Fundamentals with no explanation. I added all of the text [3] plus one new requirement pretaining to internal (non-linguistic) sorting:

![image002](https://user-images.githubusercontent.com/4839211/167406380-dfb2723d-b82a-4954-bc8c-c19c1e86f2c7.png)

**Comment by r12a** [comment]
Ed nits:  require a program-internal fast deterministic sorting  ->  require a program-internal, fast, and deterministic sorting

**Comment by aphillips** [comment]
Done.
