### ISSUE TITLE
Change the rule for establishing base direction

### ISSUE THREAD

**Issue by stevenatkin** [w3c/bp-i18n-specdev#8]
http://w3c.github.io/bp-i18n-specdev/#bidi_block_change

I would make this rule a little clearer.

The content author must be able to indicate parts of the text where the base direction changes. At the block level, this should be achieved using attributes or metadata, and should not rely on Unicode control characters.

to

The content author must be able to indicate parts of the text where the base direction changes. At the block level, this should be achieved using attributes or metadata, and should not require the content author to use Unicode control characters to control direction.

**Comment by lkemmel** [comment]
In the same section, #bidi_inline_embed rule says:
"Provide attributes that allow the user to (a) create an embedded base direction or (b) override the bidirectional algorithm altogether; the attribute should allow the user to set the direction to LTR or RTL in either of these two scenarios."

I think we also need AUTO for an embedded direction, i.e.:
"Provide attributes that allow the user to (a) create an embedded direction or (b) override the bidirectional algorithm altogether; the embedded direction attribute should allow the user to set the direction to LTR, RTL, or AUTO, and the override attribute should allow the user to set the override to LTR or RTL."

**Comment by lkemmel** [comment]
In the same section, #bidi_inline_embed rule says:

"Provide attributes that allow the user to (a) create an embedded base direction or (b) override the bidirectional algorithm altogether; the attribute should allow the user to set the direction to LTR or RTL in either of these two scenarios."

It is unclear, what the word "altogether" refers to, considering the rule doesn't suggest combining _embedded direction_ and _bidi-override_ characteristics in a single attribute.

Also, _embedded direction_ should accept the AUTO value in addition to LTR and RTL.
