### ISSUE TITLE
Possibly soften requirements related to logical order over visual order.

### ISSUE THREAD

**Issue by stevenatkin** [w3c/bp-i18n-specdev#9]
http://w3c.github.io/bp-i18n-specdev/#char_logical

In general I agree that people should be using logical order, but there are many systems that are simply based upon visual order. I would like to see if we can provide a little room in the checklist/spec to accommodate this. For example, we could say that "wherever possible" one must use logical order.

**Comment by andjc** [comment]
@stevenatkin are you referring to legacy encodings or pseudo-Unicode endodings? In Unicode data storage and transmission is is the order required by Unicode, often referred to as a logical order. This distinction of a logical order to character sequences is often used in discussions of Arabic and Hebrew processing. But it is also used with respect to scripts where visual reordering of glyphs occur during rendering, and is a key distinction between Unicode based solutions and pseudo-Unicode solutions that exist . Not sure how a Unicode based system would or even could be storing or transmitting data in a visual order ... this would break font rendering, collation, searching, etc.

**Comment by stevenatkin** [comment]
If we are going to say that we require logical order for only Unicode encodings then I am ok with the requirement.

**Comment by r12a** [comment]
This document is aimed at people developing new specifications, so we want to keep the focus on doing the right thing as we go forward, which doesn't include visual encoding.

**Comment by duerst** [comment]
Steve said: "there are many systems that are simply based upon visual order"
I wonder how many such systems are still in wide use, and how important they are. Any kind of data exchange with the 'modern' world of logical order must be quite a pain.
Also, it is not impossible to 'fake' visual order in Unicode by using bdo, so if it's really needed, then it can be done.
I also agree a lot with Richard's point of us going forward.

**Comment by tomerm** [comment]
There is a huge amount of systems which are using visual data. We are talking about mainframe based systems (mostly in banking and insurance industries) in geographies in which bidirectional scripts are used (mostly Northern Africa, Middle East and Israel). 

Visual data is associated with order of characters / text segments in text buffer (**not** to encoding). Technically speaking visual data can appear in any encoding. 

As apps and development tools working with visual data (mainframe world) are moving to cloud means to properly work with this data are being developed. It is obviously possible to "fake" visual data in many ways (i.e. using bdo as was pointed out above). However putting strict restrictions on working with logical data, completely leaves out mainframe world from modern realities ( technology / architectures).
